name             'rb-net-tools'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures redborder-net-tools on redborder proxy nodes'
version          '0.0.1'
